LOAD DATA LOCAL INFILE 'Instructor.csv' INTO TABLE instructor FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n';
LOAD DATA LOCAL INFILE 'Class.csv' INTO TABLE class FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n';
LOAD DATA LOCAL INFILE 'Student.csv' INTO TABLE student FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE 'EvaluationCheck.csv' INTO TABLE evaluationCheck FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n';
LOAD DATA LOCAL INFILE 'QuestionBank.csv' INTO TABLE questionBank FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n';
LOAD DATA LOCAL INFILE 'qa.csv' INTO TABLE qa FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n';
LOAD DATA LOCAL INFILE 'QuestionLog.csv' INTO TABLE questionLog FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n';
